name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: workflow_dispatch
jobs:
  oidc_debug_claims:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Debug OIDC Claims
        uses: github/actions-oidc-debugger@main
        with:
          audience: '5a8ac58d-9557-497a-8832-90bd35e641bf'

  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: https://auth-ap-northeast-1.cloud.databricks.com/
      DATABRICKS_CLIENT_ID: df61c752-2dc8-4d30-b3f1-d6b35895cd67

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Run Databricks CLI commands
        run: databricks current-user me

