name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: https://auth-ap-northeast-1.cloud.databricks.com/
      DATABRICKS_CLIENT_ID: df61c752-2dc8-4d30-b3f1-d6b35895cd67

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Run Databricks CLI commands
        run: databricks current-user me

